import type { RulePack } from '../ruleTypes';

const JS_LANGUAGES = ['javascript', 'javascriptreact', 'typescript', 'typescriptreact'];

export const anyPack: RulePack = {
  id: 'any',
  rules: [
    {
      id: 'scan-any-aws-access-key',
      category: 'secret',
      severity: 'error',
      pattern: /\bAKIA[0-9A-Z]{16}\b/,
      message: 'Possible AWS access key ID.',
      why: 'A committed AWS access key ID can be paired with its secret key to control AWS resources.',
      fix: 'Revoke the key in IAM, rotate it, and load credentials from environment variables or a secret manager.',
    },
    {
      id: 'scan-any-aws-secret-key',
      category: 'secret',
      severity: 'error',
      pattern: /[Aa][Ww][Ss]_[Ss]ecret[A-Za-z_]*\s*[:=]\s*['"][A-Za-z0-9/+=]{40}['"]/,
      message: 'Possible AWS secret access key.',
      why: 'Hardcoded AWS secret keys grant programmatic access to your account and survive in git history.',
      fix: 'Rotate the key in IAM and read it from an environment variable or secret manager instead.',
    },
    {
      id: 'scan-any-gcp-service-account',
      category: 'secret',
      severity: 'error',
      pattern: /"type"\s*:\s*"service_account"/,
      message: 'Possible GCP service account key.',
      why: 'Service account JSON files contain a private key that can impersonate the service account.',
      fix: 'Delete the key in GCP IAM, rotate it, and use workload identity or a secret manager.',
    },
    {
      id: 'scan-any-azure-storage-key',
      category: 'secret',
      severity: 'error',
      pattern: /DefaultEndpointsProtocol=[^;\s]+;AccountKey=[A-Za-z0-9+/=]+/,
      message: 'Possible Azure storage connection string.',
      why: 'Connection strings embed the account key, giving full access to the storage account.',
      fix: 'Regenerate the storage account key in Azure and store the connection string outside the repo.',
    },
    {
      id: 'scan-any-private-key',
      category: 'secret',
      severity: 'error',
      pattern: /-----BEGIN (?:RSA|DSA|EC|OPENSSH|PGP) PRIVATE KEY-----/,
      message: 'Private key material detected.',
      why: 'Private keys in source control can be used to impersonate servers, sign code, or decrypt traffic.',
      fix: 'Remove the key from the repository, rotate it, and keep it in a file excluded from version control.',
    },
    {
      id: 'scan-any-jwt',
      category: 'secret',
      severity: 'error',
      pattern: /\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{5,}/,
      message: 'Possible hardcoded JWT.',
      why: 'A committed JSON Web Token may still be valid and can carry a user session or service identity.',
      fix: 'Revoke or rotate the token, and read it from configuration or a secret store at runtime.',
    },
    {
      id: 'scan-any-github-token',
      category: 'secret',
      severity: 'error',
      pattern: /\bgh[pousr]_[A-Za-z0-9]{36,}\b|\bgithub_pat_[A-Za-z0-9_]{20,}/,
      message: 'Possible GitHub token.',
      why: 'GitHub tokens grant repository and account access depending on their scopes.',
      fix: 'Revoke the token in GitHub settings and use a secret manager or environment variable.',
    },
    {
      id: 'scan-any-gitlab-token',
      category: 'secret',
      severity: 'error',
      pattern: /\bglpat-[A-Za-z0-9_-]{20,}/,
      message: 'Possible GitLab personal access token.',
      why: 'GitLab personal access tokens can read or write repositories and CI settings.',
      fix: 'Revoke the token in GitLab and inject it from a masked CI variable or secret manager.',
    },
    {
      id: 'scan-any-slack-token',
      category: 'secret',
      severity: 'error',
      pattern: /\bxox[baprs]-[A-Za-z0-9-]{10,}/,
      message: 'Possible Slack token.',
      why: 'Slack tokens can read messages and act as the app or workspace bot.',
      fix: 'Revoke the token in the Slack app settings and load it from an environment variable.',
    },
    {
      id: 'scan-any-stripe-key',
      category: 'secret',
      severity: 'error',
      pattern: /\bsk_(?:live|test)_[A-Za-z0-9]{16,}\b/,
      message: 'Possible Stripe secret key.',
      why: 'A Stripe secret key allows charges, refunds, and customer data access.',
      fix: 'Roll the key in the Stripe dashboard and keep it server-side in a secret store.',
    },
    {
      id: 'scan-any-sendgrid-key',
      category: 'secret',
      severity: 'error',
      pattern: /\bSG\.[A-Za-z0-9_-]{16,}/,
      message: 'Possible SendGrid API key.',
      why: 'A SendGrid key can send mail as your domain and read account statistics.',
      fix: 'Delete the key in SendGrid and store the new key outside the repository.',
    },
    {
      id: 'scan-any-twilio-key',
      category: 'secret',
      severity: 'error',
      pattern: /\bSK[0-9a-fA-F]{32}\b/,
      message: 'Possible Twilio API key.',
      why: 'Twilio API keys can send messages and place calls billed to your account.',
      fix: 'Revoke the key in the Twilio console and load the replacement from a secret store.',
    },
    {
      id: 'scan-any-npm-token',
      category: 'secret',
      severity: 'error',
      pattern: /\bnpm_[A-Za-z0-9]{36}\b/,
      message: 'Possible npm access token.',
      why: 'An npm token can publish packages and change registry settings for your account or org.',
      fix: 'Revoke the token on npmjs.com and use a scoped token in CI secrets only.',
    },
    {
      id: 'scan-any-pypi-token',
      category: 'secret',
      severity: 'error',
      pattern: /\bpypi-[A-Za-z0-9_-]{20,}/,
      message: 'Possible PyPI API token.',
      why: 'A PyPI token can publish or yank releases for the projects it is scoped to.',
      fix: 'Revoke the token in PyPI account settings and inject the replacement from CI secrets.',
    },
    {
      id: 'scan-any-digitalocean-token',
      category: 'secret',
      severity: 'error',
      pattern: /\bdop_v1_[0-9a-f]{64}\b/,
      message: 'Possible DigitalOcean token.',
      why: 'DigitalOcean tokens can manage droplets, DNS, and billing resources.',
      fix: 'Revoke the token in the DigitalOcean control panel and rotate any affected credentials.',
    },
    {
      id: 'scan-any-telegram-bot-token',
      category: 'secret',
      severity: 'error',
      pattern: /\b[0-9]{8,10}:AA[A-Za-z0-9_-]{33}/,
      message: 'Possible Telegram bot token.',
      why: 'Anyone with the bot token can control the bot and read its messages.',
      fix: 'Revoke the token with BotFather and store the new token in a secret manager.',
    },
    {
      id: 'scan-any-discord-webhook',
      category: 'secret',
      severity: 'error',
      pattern: /https:\/\/(?:discord|discordapp)\.com\/api\/webhooks\/[0-9]+\/[A-Za-z0-9_-]+/,
      message: 'Discord webhook URL detected.',
      why: 'Anyone with the webhook URL can post messages into the channel.',
      fix: 'Delete the webhook in Discord channel settings and keep the new URL server-side.',
    },
    {
      id: 'scan-any-db-url-password',
      category: 'secret',
      severity: 'error',
      pattern: /\b(?:postgres|postgresql|mysql|mongodb(?:\+srv)?|redis|amqp):\/\/[^:\s/]+:[^@\s]+@/,
      message: 'Database URL with an inline password.',
      why: 'Connection strings with passwords leak credentials into logs, repositories, and error reports.',
      fix: 'Move the credentials into environment variables or a secret manager and rotate the password.',
    },
    {
      id: 'scan-any-generic-secret',
      category: 'secret',
      severity: 'error',
      pattern: /(?:[Pp]assword|[Pp]asswd|[Ss]ecret|[Aa]pi[_-]?[Kk]ey|[Aa]pikey|[Tt]oken)\s*[:=]\s*['"][^'"\n]{8,}['"]/,
      message: 'Hardcoded credential-like value.',
      why: 'Secrets written as string literals end up in source control, build artifacts, and logs.',
      fix: 'Replace the literal with an environment variable or secret manager lookup and rotate the value.',
    },
    {
      id: 'scan-any-http-url',
      category: 'hotspot',
      severity: 'info',
      pattern: /\bhttp:\/\/[^\s'"<>)\]]+/,
      message: 'Plain http URL.',
      why: 'Traffic over http is unencrypted and can be read or modified in transit.',
      fix: 'Use https when the server supports it, or confirm the endpoint is local and trusted.',
    },
    {
      id: 'scan-any-todo-comment',
      category: 'smell',
      severity: 'info',
      pattern: /(?:\/\/|#|<!--|\/\*|--)\s*(?:TODO|FIXME)\b[^\n]*/,
      message: 'TODO/FIXME left in code.',
      why: 'Unresolved markers hide work that was intended but never finished.',
      fix: 'Resolve the item, file a tracked issue, or remove the comment.',
    },
    {
      id: 'scan-any-commented-code',
      category: 'smell',
      severity: 'info',
      pattern: /^[^\S\n]*(?:\/\/|#)\s*[^\n]*(?:;\s*$|\)\s*$|\bfunction\b|\bdef\b|\bif\s*\()/,
      message: 'Comment that looks like disabled code.',
      why: 'Commented-out code drifts from the real implementation and confuses readers.',
      fix: 'Delete it — version control keeps the history — or restore it behind a real feature flag.',
    },
    {
      id: 'scan-any-debugger',
      category: 'bug',
      severity: 'warning',
      pattern: /\bdebugger\b|breakpoint\(\)/,
      message: 'Debugger breakpoint left in code.',
      why: 'A paused debugger halts execution and can ship to production if not removed.',
      fix: 'Remove the debugger statement or guard it behind a development-only check.',
    },
    {
      id: 'scan-assignment-in-condition',
      category: 'bug',
      severity: 'warning',
      languages: [...JS_LANGUAGES, 'java'],
      pattern: /\bif\s*\([^=!<>\n]*[^=!<>\n]=(?![=>])[^=\n]/,
      message: 'Assignment used as a condition.',
      why: 'A single = assigns instead of comparing, so the condition tests the assigned value and usually hides a typo.',
      fix: 'Use == or === for the comparison, or move the assignment before the if.',
    },
    {
      id: 'scan-float-equality',
      category: 'bug',
      severity: 'warning',
      languages: [...JS_LANGUAGES, 'java', 'python'],
      pattern: /[=!]=+\s*\d+\.\d+/,
      message: 'Floating-point value compared for exact equality.',
      why: 'Binary floating point cannot represent most decimal fractions exactly, so an equality test can fail for values that look equal.',
      fix: 'Compare with a tolerance, e.g. Math.abs(a - b) < 1e-9, or use an exact decimal type.',
    },
    {
      id: 'scan-secrets-in-logs',
      category: 'vulnerability',
      severity: 'warning',
      languages: [...JS_LANGUAGES, 'python', 'java'],
      pattern:
        /\b(?:console\.log|print|log(?:ger)?\.\w+|System\.out\.\w+)\s*\([^)\n]*(?:[Pp]assword|[Ss]ecret|[Tt]oken|[Aa]pi_?[Kk]ey|[Cc]redential)/,
      message: 'Credential-like value written to a log.',
      why: 'Logs are widely readable and retained, so passwords and tokens written to them leak beyond the process.',
      fix: 'Remove the value from the log call or mask it before logging.',
    },
    {
      id: 'scan-cookie-flags',
      category: 'vulnerability',
      severity: 'warning',
      languages: [...JS_LANGUAGES, 'python'],
      pattern:
        /\b(?:res\.cookie|[Ss]et[Cc]ookie|response\.set_cookie)\s*\((?![^\n]*(?:[Ss]ecure|[Hh]ttp[Oo]nly|[Ss]ame[Ss]ite))/,
      message: 'Cookie set without secure, httpOnly, or sameSite flags.',
      why: 'A cookie without these flags can be read by scripts or sent over plain HTTP, which enables session theft.',
      fix: 'Set secure: true, httpOnly: true, and an explicit sameSite value on the cookie.',
    },
    {
      id: 'scan-csrf-disabled',
      category: 'vulnerability',
      severity: 'warning',
      languages: [...JS_LANGUAGES, 'python'],
      pattern: /csrf\(\)\.disable\(\)|@csrf_exempt/,
      message: 'CSRF protection is disabled.',
      why: 'Without CSRF protection, another site can trigger authenticated state-changing requests on behalf of the user.',
      fix: 'Keep CSRF middleware enabled and exempt only endpoints that are genuinely safe.',
    },
    {
      id: 'scan-platform-paths',
      category: 'smell',
      severity: 'info',
      languages: [...JS_LANGUAGES, 'python', 'java', 'go'],
      pattern: /"\\\\"|"C:\\\\/,
      message: 'Hardcoded platform-specific path.',
      why: 'A path that assumes a drive letter or backslash separator fails on other operating systems.',
      fix: 'Build paths with the platform API, such as path.join, os.path.join, or Paths.get.',
    },
    {
      id: 'scan-empty-class',
      category: 'smell',
      severity: 'info',
      languages: [...JS_LANGUAGES, 'python', 'java'],
      pattern: /class\s+\w+[^{\n]*\{\s*\}|class\s+\w+[^:\n]*:\s*\n\s*pass\b/,
      message: 'Class has no members.',
      why: 'An empty class adds a name and a file without any behavior, and is usually a leftover placeholder.',
      fix: 'Remove the class or add the members it was meant to hold.',
    },
    {
      id: 'scan-ssrf',
      category: 'vulnerability',
      severity: 'warning',
      languages: [...JS_LANGUAGES, 'python'],
      pattern: /\b(?:fetch|axios\.(?:get|post)|http\.get|https\.get|requests\.(?:get|post))\s*\(\s*[a-zA-Z_$][\w$]*\s*[,)]/,
      message: 'Outbound request target comes from a variable.',
      why: 'A URL built from user input lets an attacker make the server request internal services or metadata endpoints.',
      fix: 'Validate the URL against an allowlist of trusted hosts and block private address ranges.',
    },
    {
      id: 'scan-hotspot-crypto',
      category: 'hotspot',
      severity: 'info',
      languages: [...JS_LANGUAGES, 'java'],
      pattern: /Cipher\.getInstance\(|createCipheriv\(|crypto\.createHash\(|\b(?:AES|RSA|Sign|KeyPairGenerator)\./,
      message: 'Cryptographic API usage.',
      why: 'Crypto calls need a deliberate choice of algorithm, mode, key size, and randomness.',
      fix: 'Review the algorithm and mode, use authenticated encryption, and generate keys with a secure RNG.',
    },
    {
      id: 'scan-hotspot-file-access',
      category: 'hotspot',
      severity: 'info',
      languages: [...JS_LANGUAGES, 'python', 'java'],
      pattern: /fs\.(?:readFile|writeFile|unlink|open)\s*\(|\bFiles\.(?:read|write|delete)\w*\s*\(|\bopen\s*\(/,
      message: 'File system access.',
      why: 'File operations on paths derived from input can read or overwrite unintended files.',
      fix: 'Resolve paths against a fixed root and reject values that escape it.',
    },
  ],
};
