import type { RulePack } from '../ruleTypes';

export const csharpPack: RulePack = {
  id: 'csharp',
  languages: ['csharp'],
  rules: [
    {
      id: 'scan-csharp-empty-catch',
      category: 'bug',
      severity: 'warning',
      pattern: /\bcatch\s*\(\s*Exception(?:\s+\w+)?\s*\)\s*\{\s*\}/,
      message: 'Exception caught and ignored.',
      why: 'An empty handler swallows failures, so bugs surface later with no trace of the cause.',
      fix: 'Log the exception with context, handle it meaningfully, or remove the catch.',
    },
    {
      id: 'scan-csharp-weak-hash',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /\b(?:MD5|SHA1)\.Create\s*\(/,
      message: 'MD5/SHA-1 used for hashing.',
      why: 'Both algorithms have practical collision attacks and are too fast for password hashing.',
      fix: 'Use SHA256.Create() for data and a slow KDF such as PBKDF2, bcrypt, or Argon2 for passwords.',
    },
    {
      id: 'scan-csharp-new-random',
      category: 'hotspot',
      severity: 'info',
      pattern: /\bnew\s+Random\s*\(/,
      message: 'System.Random is not cryptographically secure.',
      why: 'Its sequence is predictable, which matters for tokens, keys, and security decisions.',
      fix: 'Use RandomNumberGenerator.GetBytes or GetInt32 for anything security-related.',
    },
    {
      id: 'scan-csharp-process-start',
      category: 'vulnerability',
      severity: 'error',
      pattern: /\bProcess\.Start\s*\([^\n]*(?:\+|[$@]{1,2}"[^"\n]*\{)/,
      message: 'Process started with an interpolated or concatenated command.',
      why: 'Untrusted values can inject arguments or shell metacharacters into the command line.',
      fix: 'Use ProcessStartInfo with ArgumentList and validate every argument.',
    },
    {
      id: 'scan-csharp-binary-formatter',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /\bBinaryFormatter\b/,
      message: 'BinaryFormatter deserialization.',
      why: 'Deserializing untrusted data with BinaryFormatter can execute arbitrary code and is unsafe by design.',
      fix: 'Use System.Text.Json or another data-only serializer and migrate persisted payloads.',
    },
    {
      id: 'scan-csharp-sql-concatenation',
      category: 'vulnerability',
      severity: 'error',
      pattern: /\bnew\s+SqlCommand\s*\([^\n]*(?:\+|[$@]{1,2}"[^"\n]*\{)/,
      message: 'SqlCommand built with concatenation or interpolation.',
      why: 'Embedding values directly in the command text enables SQL injection.',
      fix: 'Use SqlParameter objects and bind values instead of building the query as a string.',
    },
    {
      id: 'scan-csharp-task-blocking',
      category: 'bug',
      severity: 'warning',
      pattern: /\.Result\b|\.Wait\s*\(\s*\)/,
      message: 'Task blocked synchronously.',
      why: 'Blocking on .Result or .Wait() can deadlock in contexts with a synchronization context.',
      fix: 'Await the task instead, and make the calling method async.',
    },
    {
      id: 'scan-csharp-rethrow-ex',
      category: 'bug',
      severity: 'warning',
      pattern: /\bthrow\s+ex\s*;/,
      message: 'Exception rethrown with throw ex.',
      why: 'throw ex resets the stack trace, hiding where the exception actually came from.',
      fix: 'Use a bare throw; to preserve the original stack trace.',
    },
    {
      id: 'scan-csharp-async-void',
      category: 'bug',
      severity: 'warning',
      pattern: /\basync\s+void\b/,
      message: 'async void method.',
      why: 'Callers cannot await or catch exceptions from async void, so failures crash the process.',
      fix: 'Return Task, except for event handlers where async void is required.',
    },
    {
      id: 'scan-csharp-console-write-line',
      category: 'smell',
      severity: 'info',
      pattern: /\bConsole\.WriteLine\s*\(/,
      message: 'Console output left in code.',
      why: 'Ad-hoc writing clutters output and can leak data in production.',
      fix: 'Use ILogger or another logging abstraction, or remove the call.',
    },
    {
      id: 'scan-csharp-gc-collect',
      category: 'smell',
      severity: 'info',
      pattern: /\bGC\.Collect\s*\(/,
      message: 'Explicit garbage collection.',
      why: 'Forcing a collection is expensive and usually indicates a resource management problem.',
      fix: 'Remove the call and dispose unmanaged resources with using or Dispose.',
    },
  ],
};
