import type { RulePack } from '../ruleTypes';

export const goPack: RulePack = {
  id: 'go',
  languages: ['go'],
  rules: [
    {
      id: 'scan-go-insecure-skip-verify',
      category: 'vulnerability',
      severity: 'error',
      pattern: /InsecureSkipVerify\s*:\s*true/,
      message: 'TLS certificate verification disabled.',
      why: 'InsecureSkipVerify skips certificate checks, so any man-in-the-middle can impersonate the server.',
      fix: 'Remove the option and configure the correct root CAs or pin the expected certificate.',
    },
    {
      id: 'scan-go-exec-command',
      category: 'vulnerability',
      severity: 'error',
      pattern: /\bexec\.Command\s*\([^\n]*(?:fmt\.Sprintf|\+)/,
      message: 'Command built with formatting or concatenation.',
      why: 'Interpolated values can inject extra arguments or shell metacharacters into the command.',
      fix: 'Pass each argument as its own string and validate any user-controlled value.',
    },
    {
      id: 'scan-go-weak-crypto-import',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /"(?:crypto\/md5|crypto\/sha1)"/,
      message: 'MD5/SHA-1 package imported.',
      why: 'Both algorithms have practical collision attacks and must not protect passwords or signatures.',
      fix: 'Import crypto/sha256 or better, and use bcrypt or argon2 for passwords.',
    },
    {
      id: 'scan-go-math-rand-import',
      category: 'hotspot',
      severity: 'info',
      pattern: /"math\/rand(?:\/v2)?"/,
      message: 'math/rand package imported.',
      why: 'math/rand is seeded predictably and must not generate tokens, keys, or security decisions.',
      fix: 'Use crypto/rand for anything security-related.',
    },
    {
      id: 'scan-go-panic',
      category: 'smell',
      severity: 'info',
      pattern: /\bpanic\s*\(/,
      message: 'panic() called.',
      why: 'Panics abort the request or program and are usually better returned as errors.',
      fix: 'Return an error with context and let the caller decide how to handle it.',
    },
    {
      id: 'scan-go-fmt-print',
      category: 'smell',
      severity: 'info',
      pattern: /\bfmt\.Print(?:f|ln)?\s*\(/,
      message: 'fmt print left in code.',
      why: 'Ad-hoc printing clutters output and can leak data in production.',
      fix: 'Use the log or slog package, or remove the call.',
    },
    {
      id: 'scan-go-http-get-plaintext',
      category: 'hotspot',
      severity: 'info',
      pattern: /\bhttp\.Get\s*\(\s*"http:\/\//,
      message: 'http.Get over plaintext http.',
      why: 'Traffic over http is unencrypted and can be read or modified in transit.',
      fix: 'Use an https URL when the server supports it.',
    },
    {
      id: 'scan-go-ignored-error',
      category: 'bug',
      severity: 'warning',
      pattern: /^[^\S\n]*_[^\S\n]*=[^\S\n]*\w+/,
      message: 'Result discarded with the blank identifier.',
      why: 'Assigning to _ throws away the value without handling the failure it may carry.',
      fix: 'Check the error, or handle the value instead of discarding it.',
    },
  ],
};
