import type { RulePack } from '../ruleTypes';

export const iacPack: RulePack = {
  id: 'iac',
  rules: [
    {
      id: 'scan-iac-docker-latest-tag',
      category: 'smell',
      severity: 'warning',
      pattern: /^FROM\s+\S+:latest\b/,
      message: 'Docker base image pinned to latest.',
      why: 'The latest tag moves without warning, so builds stop being reproducible.',
      fix: 'Pin the image to a specific version or digest.',
    },
    {
      id: 'scan-iac-docker-untagged-base',
      category: 'smell',
      severity: 'warning',
      pattern: /^FROM\s+(?!scratch\b)[^\s:@]+$/,
      message: 'Docker base image has no tag.',
      why: 'An untagged image resolves to latest, so the build can change without notice.',
      fix: 'Specify an explicit version tag or digest for the base image.',
    },
    {
      id: 'scan-iac-docker-root-user',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /^USER\s+root\b/,
      message: 'Container runs as root.',
      why: 'A root container that escapes its isolation gains full control of the host.',
      fix: 'Create an unprivileged user and switch to it with the USER instruction.',
    },
    {
      id: 'scan-iac-docker-privileged',
      category: 'vulnerability',
      severity: 'error',
      pattern: /--privileged\b/,
      message: 'Container started with --privileged.',
      why: 'A privileged container has all capabilities and device access, effectively disabling isolation.',
      fix: 'Drop the flag and grant only the specific capabilities the workload needs.',
    },
    {
      id: 'scan-iac-docker-socket-mount',
      category: 'vulnerability',
      severity: 'error',
      pattern: /docker\.sock/,
      message: 'Docker socket exposed.',
      why: 'Access to docker.sock lets a container control the Docker daemon and take over the host.',
      fix: 'Avoid mounting the socket; use a restricted API proxy or rootless alternative if needed.',
    },
    {
      id: 'scan-iac-docker-add',
      category: 'smell',
      severity: 'info',
      pattern: /^ADD\s/,
      message: 'ADD used instead of COPY.',
      why: 'ADD can fetch URLs and unpack archives implicitly, which is rarely intended.',
      fix: 'Use COPY for local files and fetch remote content explicitly with curl or wget.',
    },
    {
      id: 'scan-iac-curl-pipe-shell',
      category: 'vulnerability',
      severity: 'error',
      pattern: /curl\s+[^\n|]*\|\s*(?:ba)?sh\b/,
      message: 'Remote script piped into a shell.',
      why: 'The downloaded script runs with no verification, so a compromised server controls the build.',
      fix: 'Download the script, verify its checksum or signature, then execute it.',
    },
    {
      id: 'scan-iac-docker-env-secret',
      category: 'secret',
      severity: 'error',
      pattern: /^ENV\s+.*(?:PASSWORD|SECRET|TOKEN|API_KEY)=/,
      message: 'Secret passed through ENV.',
      why: 'Values set with ENV are baked into image layers and visible to anyone with the image.',
      fix: 'Inject secrets at runtime with build mounts or a secret manager instead.',
    },
    {
      id: 'scan-iac-docker-expose-ssh',
      category: 'hotspot',
      severity: 'warning',
      pattern: /^EXPOSE\s+22\b/,
      message: 'SSH port exposed from the image.',
      why: 'Running an SSH daemon in a container widens the attack surface and is rarely needed.',
      fix: 'Remove the EXPOSE 22 instruction and use exec or a debug sidecar for access.',
    },
    {
      id: 'scan-iac-k8s-privileged',
      category: 'vulnerability',
      severity: 'error',
      pattern: /privileged\s*:\s*true\b/,
      message: 'Kubernetes container runs privileged.',
      why: 'A privileged pod has full host capabilities and can compromise the node.',
      fix: 'Set privileged to false and allow only the specific capabilities required.',
    },
    {
      id: 'scan-iac-k8s-host-namespace',
      category: 'vulnerability',
      severity: 'error',
      pattern: /\bhost(?:Network|PID|IPC)\s*:\s*true\b/,
      message: 'Pod shares a host namespace.',
      why: 'hostNetwork, hostPID, and hostIPC expose node processes and traffic to the container.',
      fix: 'Disable the host namespace unless the workload is a trusted node-level agent.',
    },
    {
      id: 'scan-iac-k8s-root-user',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /runAsUser\s*:\s*0\b/,
      message: 'Pod runs as UID 0.',
      why: 'Running as root inside the container increases the impact of any container escape.',
      fix: 'Set runAsUser to a non-zero UID and set runAsNonRoot to true.',
    },
    {
      id: 'scan-iac-k8s-host-path',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /\bhostPath\s*:/,
      message: 'hostPath volume mounted.',
      why: 'A hostPath mount exposes node files and can be used to escape the container.',
      fix: 'Use a PersistentVolume or projected volume instead of hostPath.',
    },
    {
      id: 'scan-iac-k8s-latest-image',
      category: 'smell',
      severity: 'warning',
      pattern: /\bimage\s*:\s*\S+:latest\b/,
      message: 'Container image pinned to latest.',
      why: 'The latest tag changes without warning, so deployments stop being reproducible.',
      fix: 'Pin the image to an immutable version tag or digest.',
    },
    {
      id: 'scan-iac-k8s-wildcard-verbs',
      category: 'vulnerability',
      severity: 'error',
      pattern: /verbs\s*:\s*\[?\s*["']\*/,
      message: 'RBAC rule grants all verbs.',
      why: 'A wildcard verb on a resource lets the role perform every action, including delete and escalate.',
      fix: 'List only the verbs the workload actually needs.',
    },
    {
      id: 'scan-iac-k8s-load-balancer',
      category: 'hotspot',
      severity: 'info',
      pattern: /\btype\s*:\s*LoadBalancer\b/,
      message: 'Service exposed through a load balancer.',
      why: 'A LoadBalancer service is publicly reachable by default and costs money.',
      fix: 'Confirm the service must be public; otherwise use ClusterIP or an internal load balancer.',
    },
    {
      id: 'scan-iac-k8s-automount-token',
      category: 'hotspot',
      severity: 'info',
      pattern: /automountServiceAccountToken\s*:\s*true\b/,
      message: 'Service account token automounted.',
      why: 'A mounted token lets any process in the pod talk to the Kubernetes API as that account.',
      fix: 'Set automountServiceAccountToken to false unless the pod needs API access.',
    },
    {
      id: 'scan-iac-open-cidr',
      category: 'vulnerability',
      severity: 'error',
      pattern: /0\.0\.0\.0\/0/,
      message: 'Firewall or route open to the whole internet.',
      why: '0.0.0.0/0 allows traffic from any address, exposing the resource publicly.',
      fix: 'Restrict the CIDR to the specific networks that need access.',
    },
    {
      id: 'scan-iac-public-read-acl',
      category: 'vulnerability',
      severity: 'error',
      pattern: /\bacl\s*=\s*"public-read"/,
      message: 'Storage bucket set to public-read.',
      why: 'A public-read ACL exposes every object in the bucket to the internet.',
      fix: 'Remove the public ACL and serve content through a controlled endpoint.',
    },
    {
      id: 'scan-iac-encryption-disabled',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /\bencrypted\s*=\s*false\b/,
      message: 'Encryption explicitly disabled.',
      why: 'Unencrypted storage exposes data if the underlying disk or snapshot leaks.',
      fix: 'Set encrypted to true and manage the key through a KMS.',
    },
    {
      id: 'scan-iac-iam-wildcard-allow',
      category: 'vulnerability',
      severity: 'error',
      pattern: /Effect:\s*"Allow"[\s\S]{0,120}"\*"/,
      message: 'IAM policy allows a wildcard.',
      why: 'Allow on "*" grants every action or resource, far beyond what the workload needs.',
      fix: 'Replace the wildcard with the specific actions and resources required.',
    },
    {
      id: 'scan-iac-publicly-accessible',
      category: 'vulnerability',
      severity: 'error',
      pattern: /\bpublicly_accessible\s*=\s*true\b/,
      message: 'Database marked publicly accessible.',
      why: 'A publicly accessible database can be reached from the internet and attacked directly.',
      fix: 'Set publicly_accessible to false and access the database through a private network.',
    },
  ],
};
