import type { RulePack } from '../ruleTypes';

export const javaPack: RulePack = {
  id: 'java',
  languages: ['java'],
  rules: [
    {
      id: 'scan-java-print-stack-trace',
      category: 'smell',
      severity: 'info',
      pattern: /\.printStackTrace\s*\(\)/,
      message: 'printStackTrace() writes directly to stderr.',
      why: 'Printing traces bypasses the logging framework and can leak internals to users.',
      fix: 'Log the exception with your logger and include the context needed to diagnose it.',
    },
    {
      id: 'scan-java-system-out',
      category: 'smell',
      severity: 'info',
      pattern: /\bSystem\.out\.print(?:ln)?\s*\(/,
      message: 'System.out output left in code.',
      why: 'Console printing clutters output, is slow, and can leak data in production.',
      fix: 'Use a logging framework with levels and remove the direct print call.',
    },
    {
      id: 'scan-java-boxing-constructor',
      category: 'smell',
      severity: 'info',
      pattern: /\bnew\s+(?:Integer|Long|Double|Float)\s*\(/,
      message: 'Boxing via a deprecated constructor.',
      why: 'Constructors like new Integer() are deprecated and allocate a new object instead of using the cache.',
      fix: 'Use the valueOf factory method or autoboxing, e.g. Integer.valueOf(value).',
    },
    {
      id: 'scan-java-bigdecimal-double',
      category: 'bug',
      severity: 'warning',
      pattern: /\bnew\s+BigDecimal\s*\(\s*(?:[0-9][0-9_]*(?:\.[0-9]*[dDfF]?|[eE][+-]?[0-9]+[dDfF]?|[dDfF])|\.[0-9]+[dDfF]?)\s*\)/,
      message: 'BigDecimal constructed from a floating-point literal.',
      why: 'Binary floating point cannot represent most decimal values exactly, so the BigDecimal starts with a hidden rounding error.',
      fix: 'Use the String constructor, e.g. new BigDecimal("0.1").',
    },
    {
      id: 'scan-java-legacy-collection',
      category: 'smell',
      severity: 'info',
      pattern: /\b(?:Vector|Hashtable)\s*</,
      message: 'Legacy synchronized collection used.',
      why: 'Vector and Hashtable lock on every operation and are usually slower than their modern replacements.',
      fix: 'Use ArrayList, HashMap, or a concurrent collection such as ConcurrentHashMap.',
    },
    {
      id: 'scan-java-finalize',
      category: 'bug',
      severity: 'warning',
      pattern: /\bvoid\s+finalize\s*\(\s*\)/,
      message: 'finalize() override.',
      why: 'Finalizers run at an unpredictable time, may never run, and can resurrect objects or leak resources.',
      fix: 'Release resources with try-with-resources, an explicit close method, or Cleaner.',
    },
    {
      id: 'scan-java-thread-run',
      category: 'bug',
      severity: 'info',
      pattern: /\bnew\s+Thread\s*\([^)]*\)\s*\.run\s*\(|\bThread\b[^\n]*\.run\s*\(\s*\)/,
      message: 'Thread.run() called instead of start().',
      why: 'Calling run() executes the body synchronously on the current thread, so no concurrency happens.',
      fix: 'Call start() to launch a new thread, or submit the task to an ExecutorService.',
    },
    {
      id: 'scan-java-catch-throwable',
      category: 'bug',
      severity: 'warning',
      pattern: /\bcatch\s*\(\s*Throwable\b/,
      message: 'catch (Throwable) catches every failure.',
      why: 'It also catches Error conditions such as OutOfMemoryError that should normally propagate.',
      fix: 'Catch the specific exceptions you can handle, or at least Exception instead of Throwable.',
    },
    {
      id: 'scan-java-weak-message-digest',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /MessageDigest\.getInstance\s*\(\s*["'](?:MD5|SHA-1)["']/,
      message: 'MD5/SHA-1 used for hashing.',
      why: 'Both algorithms have practical collision attacks and must not protect passwords or signatures.',
      fix: 'Use SHA-256 or better, and a slow password hash such as bcrypt, scrypt, or Argon2.',
    },
    {
      id: 'scan-java-weak-cipher',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /Cipher\.getInstance\s*\(\s*["'][^"'\n]*(?:DES|RC4|ECB)[^"'\n]*["']/,
      message: 'Weak cipher algorithm requested.',
      why: 'DES, RC4, and ECB mode are broken or leak patterns in the plaintext.',
      fix: 'Use AES/GCM/NoPadding with a random IV, or another authenticated modern cipher.',
    },
    {
      id: 'scan-java-trust-manager',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /setDefaultHostnameVerifier|checkServerTrusted/,
      message: 'Custom TLS trust handling.',
      why: 'Overridden trust managers and hostname verifiers often accept any certificate, enabling man-in-the-middle attacks.',
      fix: 'Validate certificates against the system or a pinned trust store instead of bypassing the check.',
    },
    {
      id: 'scan-java-runtime-exec',
      category: 'vulnerability',
      severity: 'error',
      pattern: /\bRuntime\.getRuntime\s*\(\s*\)\s*\.exec\s*\(/,
      message: 'Runtime.exec() starts an external process.',
      why: 'The command string is parsed by the OS shell, so unescaped input can inject commands.',
      fix: 'Use ProcessBuilder with a separate argument list and validate every argument.',
    },
    {
      id: 'scan-java-object-input-stream',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /\bnew\s+ObjectInputStream\s*\(/,
      message: 'Java native deserialization.',
      why: 'Reading untrusted serialized objects can execute arbitrary code through gadget chains.',
      fix: 'Use a data-only format such as JSON, or validate classes with an ObjectInputFilter.',
    },
    {
      id: 'scan-java-static-date-format',
      category: 'bug',
      severity: 'info',
      pattern: /\bstatic\b[^\n;=]*\bSimpleDateFormat\b/,
      message: 'SimpleDateFormat stored in a static field.',
      why: 'SimpleDateFormat is not thread-safe, so shared instances produce corrupted dates or exceptions.',
      fix: 'Use DateTimeFormatter, or create a new formatter per thread or call.',
    },
    {
      id: 'scan-java-sql-concatenation',
      category: 'vulnerability',
      severity: 'error',
      pattern: /\.(?:executeQuery|executeUpdate)\s*\([^\n]*\+/,
      message: 'SQL statement built with string concatenation.',
      why: 'Interpolating values into a query enables SQL injection.',
      fix: 'Use a PreparedStatement and bind parameters instead of concatenating values.',
    },
    {
      id: 'scan-java-equals-strings',
      category: 'bug',
      severity: 'warning',
      pattern: /==\s*"|"\s*==/,
      message: 'String compared with ==.',
      why: '== compares object references, so two equal strings created separately are not equal.',
      fix: 'Use .equals() for string values, or Objects.equals for nullable strings.',
    },
    {
      id: 'scan-java-getclass-equality',
      category: 'bug',
      severity: 'warning',
      pattern: /\.getClass\(\)\s*[!=]=/,
      message: 'Class compared with == or !=.',
      why: 'getClass() equality fails for subclasses and proxies, so the check can reject valid instances.',
      fix: 'Use instanceof or Class.isAssignableFrom when the check should allow subclasses.',
    },
    {
      id: 'scan-throw-generic',
      category: 'smell',
      severity: 'info',
      pattern: /\bthrow\s+new\s+(?:Exception|RuntimeException|Error)\s*\(/,
      message: 'Generic exception thrown.',
      why: 'Throwing Exception, RuntimeException, or Error gives callers nothing specific to catch and hides the failure type.',
      fix: 'Throw a specific exception type, or a custom exception that carries context.',
    },
    {
      id: 'scan-stringbuffer',
      category: 'smell',
      severity: 'info',
      pattern: /\bnew\s+StringBuffer\s*\(/,
      message: 'StringBuffer used instead of StringBuilder.',
      why: 'StringBuffer synchronizes every operation, which is unnecessary unless the buffer is shared across threads.',
      fix: 'Use StringBuilder for local, single-threaded building.',
    },
    {
      id: 'scan-deprecated-api',
      category: 'bug',
      severity: 'warning',
      pattern: /\bThread\.(?:stop|suspend|resume)\s*\(|Runtime\.getRuntime\(\)\.runFinalizersOnExit/,
      message: 'Deprecated and unsafe JDK API used.',
      why: 'Thread.stop, suspend, and resume can leave objects in an inconsistent state, and runFinalizersOnExit is unsafe.',
      fix: 'Interrupt the thread or use a flag for cooperative cancellation, and drop runFinalizersOnExit.',
    },
    {
      id: 'scan-default-charset',
      category: 'smell',
      severity: 'info',
      pattern: /\bnew\s+(?:InputStreamReader|OutputStreamWriter|FileReader|FileWriter)\s*\([^,()\n]*\)/,
      message: 'Reader or writer created without a charset.',
      why: 'Without an explicit charset the platform default is used, so the same file can be read differently on another machine.',
      fix: 'Pass a charset explicitly, e.g. new InputStreamReader(in, StandardCharsets.UTF_8).',
    },
    {
      id: 'scan-hotspot-reflection',
      category: 'hotspot',
      severity: 'info',
      pattern: /\bClass\.forName\s*\(|getDeclaredMethod\s*\(|getDeclaredField\s*\(/,
      message: 'Reflection API usage.',
      why: 'Reflection resolves names at runtime, can reach otherwise inaccessible code, and is hard to analyze.',
      fix: 'Confirm the inputs are trusted and prefer direct calls or a registry where possible.',
    },
  ],
};
