import type { RulePack } from '../ruleTypes';

export const phpPack: RulePack = {
  id: 'php',
  languages: ['php'],
  rules: [
    {
      id: 'scan-php-eval-assert',
      category: 'vulnerability',
      severity: 'error',
      pattern: /\beval\s*\(|\bassert\s*\(\s*\$/,
      message: 'Dynamic code evaluation.',
      why: 'eval() and string asserts execute whatever expression they are given, including attacker input.',
      fix: 'Replace the dynamic code with explicit logic or a safe data parser.',
    },
    {
      id: 'scan-php-command-execution',
      category: 'vulnerability',
      severity: 'error',
      pattern: /\b(?:system|exec|shell_exec|passthru|popen)\s*\(/,
      message: 'Shell command execution function.',
      why: 'These functions pass strings to the shell, so unescaped input can inject commands.',
      fix: 'Use escapeshellarg/escapeshellcmd with a fixed command, or avoid the shell entirely.',
    },
    {
      id: 'scan-php-weak-hash',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /\b(?:md5|sha1)\s*\(/,
      message: 'MD5/SHA-1 used for hashing.',
      why: 'Both algorithms have practical collision attacks and are far too fast for password hashing.',
      fix: 'Use password_hash() with PASSWORD_DEFAULT, and hash data with sha256 or better.',
    },
    {
      id: 'scan-php-weak-random',
      category: 'hotspot',
      severity: 'info',
      pattern: /\b(?:rand|mt_rand)\s*\(/,
      message: 'Predictable random number generator.',
      why: 'rand() and mt_rand() are not cryptographically secure and can be predicted from observed output.',
      fix: 'Use random_int() or random_bytes() for tokens, codes, and security decisions.',
    },
    {
      id: 'scan-php-unserialize',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /\bunserialize\s*\(/,
      message: 'PHP object deserialization.',
      why: 'Unserializing untrusted input can trigger magic methods and instantiate dangerous objects.',
      fix: 'Use json_decode() for data, or restrict classes with the allowed_classes option.',
    },
    {
      id: 'scan-php-error-reporting-off',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /error_reporting\s*\(\s*0\s*\)/,
      message: 'Error reporting disabled.',
      why: 'Suppressing all errors hides failures and can leave sensitive behavior unmonitored.',
      fix: 'Log errors instead of disabling them, and keep display_errors off in production.',
    },
    {
      id: 'scan-php-extract',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /\bextract\s*\(/,
      message: 'extract() imports variables from an array.',
      why: 'User-controlled keys can overwrite existing variables and change program behavior.',
      fix: 'Read the array keys you expect explicitly and assign them to named variables.',
    },
    {
      id: 'scan-php-debug-output',
      category: 'smell',
      severity: 'info',
      pattern: /\b(?:var_dump|print_r)\s*\(/,
      message: 'Debug output left in code.',
      why: 'Dumping internals can leak data to users and clutters responses.',
      fix: 'Remove the call or send the data to a logger behind a debug flag.',
    },
    {
      id: 'scan-php-sql-concatenation',
      category: 'vulnerability',
      severity: 'error',
      pattern: /\b(?:mysqli_query|query)\s*\([^\n]*(?:\.\s*\$|"[^"\n]*\$)/,
      message: 'SQL statement built from concatenation or interpolation.',
      why: 'Embedding variables directly in a query enables SQL injection.',
      fix: 'Use prepared statements with bound parameters instead of building the query as a string.',
    },
    {
      id: 'scan-php-loose-comparison-input',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /(?:\$_(?:GET|POST|REQUEST)\b[^\n]*?(?<![=!<>])==(?!=)|(?<![=!<>])==(?!=)[^\n]*?\$_(?:GET|POST|REQUEST)\b)/,
      message: 'Loose comparison against request input.',
      why: 'PHP type juggling makes == treat values like "0e123" and "0" as equal, bypassing checks.',
      fix: 'Use === or !== and validate the input type before comparing.',
    },
  ],
};
