import type { RulePack } from '../ruleTypes';

export const pythonPack: RulePack = {
  id: 'python',
  languages: ['python'],
  rules: [
    {
      id: 'scan-py-eval-exec',
      category: 'vulnerability',
      severity: 'error',
      pattern: /\b(?:eval|exec)\s*\(/,
      message: 'eval()/exec() runs arbitrary code.',
      why: 'Any input that reaches these calls can execute attacker-controlled Python.',
      fix: 'Use ast.literal_eval for data or replace the dynamic code with explicit logic.',
    },
    {
      id: 'scan-py-os-system',
      category: 'vulnerability',
      severity: 'error',
      pattern: /\bos\.system\s*\(/,
      message: 'os.system() invokes a shell.',
      why: 'The command string is passed to the shell, so unescaped input can inject commands.',
      fix: 'Use subprocess.run with a list of arguments and shell=False.',
    },
    {
      id: 'scan-py-subprocess-shell',
      category: 'vulnerability',
      severity: 'error',
      pattern: /subprocess[^\n]*shell\s*=\s*True/,
      message: 'subprocess called with shell=True.',
      why: 'shell=True interprets the command through the shell and enables command injection.',
      fix: 'Pass the program and arguments as a list and keep shell=False.',
    },
    {
      id: 'scan-py-pickle',
      category: 'vulnerability',
      severity: 'error',
      pattern: /\b(?:pickle|cPickle)\.loads?\s*\(/,
      message: 'Deserializing pickle data can execute code.',
      why: 'Pickle payloads can construct arbitrary objects and run code during unpickling.',
      fix: 'Use JSON or another data-only format, or verify a signature before unpickling trusted data.',
    },
    {
      id: 'scan-py-yaml-load',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /\byaml\.load\s*\((?!\s*[^)\n]*SafeLoader)/,
      message: 'yaml.load() without SafeLoader can run code.',
      why: 'The default loader can construct arbitrary Python objects from untrusted YAML.',
      fix: 'Use yaml.safe_load() or pass Loader=yaml.SafeLoader.',
    },
    {
      id: 'scan-py-weak-hash',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /\b(?:md5|sha1)\s*\(/,
      message: 'MD5/SHA-1 are weak for security use.',
      why: 'Both algorithms have practical collision attacks and should not protect passwords or signatures.',
      fix: 'Use hashlib.sha256 or better, and a slow password hash such as bcrypt or argon2.',
    },
    {
      id: 'scan-py-verify-false',
      category: 'vulnerability',
      severity: 'error',
      pattern: /\bverify\s*=\s*False/,
      message: 'TLS certificate verification disabled.',
      why: 'Skipping verification allows man-in-the-middle attacks against the request.',
      fix: 'Remove verify=False and configure the correct CA bundle instead.',
    },
    {
      id: 'scan-py-random-secret',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /(?:\b(?:token|password|passwd|secret|salt|api_key)\w*\s*=\s*[^\n]*\brandom\.|\brandom\.\w+\([^\n]*(?:token|password|passwd|secret|salt))/,
      message: 'random module used for a secret-like value.',
      why: 'The random module is seeded predictably and must not generate tokens, passwords, or salts.',
      fix: 'Use the secrets module, such as secrets.token_urlsafe().',
    },
    {
      id: 'scan-py-bare-except',
      category: 'bug',
      severity: 'warning',
      pattern: /^[^\S\n]*except\s*:/,
      message: 'Bare except catches everything.',
      why: 'It also swallows KeyboardInterrupt and SystemExit, hiding real failures.',
      fix: 'Catch the specific exceptions you expect.',
    },
    {
      id: 'scan-py-except-pass',
      category: 'bug',
      severity: 'warning',
      pattern: /\bexcept\b[^\n]*:\s*pass\b/,
      message: 'Exception silently ignored.',
      why: 'A pass handler hides errors and makes failures hard to trace.',
      fix: 'Log the exception with context or handle it explicitly.',
    },
    {
      id: 'scan-py-open-no-with',
      category: 'bug',
      severity: 'info',
      pattern: /^[^\S\n]*\w+\s*=\s*open\s*\(/,
      message: 'File opened without a with block.',
      why: 'A plain assignment can leak the file handle if an error occurs before close().',
      fix: 'Use a with open(...) as f: block so the file is always closed.',
    },
    {
      id: 'scan-py-sql-format',
      category: 'vulnerability',
      severity: 'error',
      pattern: /\b(?:execute|executemany)\s*\([^\n]*(?:f['"]|\.format\s*\(|%\s*\()/,
      message: 'SQL built with string formatting.',
      why: 'Interpolating values into SQL enables injection attacks.',
      fix: 'Pass parameters separately, e.g. cursor.execute("... WHERE id = %s", (user_id,)).',
    },
    {
      id: 'scan-py-debug-true',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /\bDEBUG\s*=\s*True/,
      message: 'DEBUG mode enabled.',
      why: 'Debug mode exposes stack traces, settings, and sometimes an interactive debugger.',
      fix: 'Drive DEBUG from an environment variable and keep it off in production.',
    },
    {
      id: 'scan-py-flask-debug',
      category: 'vulnerability',
      severity: 'warning',
      pattern: /\bapp\.run\s*\([^\n]*debug\s*=\s*True/,
      message: 'Flask app started with debug=True.',
      why: 'The Werkzeug debugger can execute code when it is reachable by untrusted users.',
      fix: 'Run with debug=False in production and control debug mode via configuration.',
    },
    {
      id: 'scan-py-print',
      category: 'smell',
      severity: 'info',
      pattern: /\bprint\s*\(/,
      message: 'print() left in code.',
      why: 'Ad-hoc printing clutters output and can leak data in production.',
      fix: 'Use the logging module or remove the call.',
    },
  ],
};
