import type { RulePack } from '../ruleTypes';

export const webPack: RulePack = {
  id: 'web',
  languages: ['html', 'css', 'xml'],
  rules: [
    {
      id: 'scan-web-img-no-alt',
      category: 'bug',
      severity: 'warning',
      languages: ['html'],
      pattern: /<img\b(?![^>]*\balt=)[^>]*>/,
      message: 'Image is missing an alt attribute.',
      why: 'Screen readers and text-only clients cannot describe the image without alternative text.',
      fix: 'Add alt text that conveys the image meaning, or alt="" for purely decorative images.',
    },
    {
      id: 'scan-web-iframe-no-title',
      category: 'bug',
      severity: 'info',
      languages: ['html'],
      pattern: /<iframe\b(?![^>]*\btitle=)[^>]*>/,
      message: 'Iframe is missing a title attribute.',
      why: 'Assistive technology uses the title to announce what the embedded frame contains.',
      fix: 'Add a short title that describes the embedded content.',
    },
    {
      id: 'scan-web-html-no-lang',
      category: 'bug',
      severity: 'warning',
      languages: ['html'],
      pattern: /<html(?![^>]*\blang=)[^>]*>/,
      message: 'Document language is not declared.',
      why: 'Without a lang attribute, screen readers may use the wrong pronunciation rules.',
      fix: 'Add a lang attribute to the html element, e.g. lang="en".',
    },
    {
      id: 'scan-web-input-no-label',
      category: 'bug',
      severity: 'info',
      languages: ['html'],
      pattern: /<input\b(?![^>]*\b(?:aria-label|id|aria-labelledby)=)[^>]*>/,
      message: 'Input has no associated label.',
      why: 'An input without a label, id, or aria-label is not announced meaningfully to assistive technology.',
      fix: 'Add a label element with a matching id, or an aria-label attribute.',
    },
    {
      id: 'scan-web-deprecated-tag',
      category: 'smell',
      severity: 'info',
      languages: ['html'],
      pattern: /<(?:center|font|marquee|blink)\b/,
      message: 'Deprecated HTML element used.',
      why: 'These elements are obsolete and may be dropped or rendered inconsistently by browsers.',
      fix: 'Replace them with CSS for layout, typography, and animation.',
    },
    {
      id: 'html-missing-viewport',
      category: 'bug',
      severity: 'info',
      languages: ['html'],
      pattern: /<meta[^>]+name=["']viewport["']/,
      fileLevel: true,
      message: 'Viewport meta tag is missing.',
      why: 'Without a viewport tag, mobile browsers render the page at desktop width and shrink it.',
      fix: 'Add <meta name="viewport" content="width=device-width, initial-scale=1"> in the head.',
    },
    {
      id: 'html-missing-title',
      category: 'bug',
      severity: 'info',
      languages: ['html'],
      pattern: /<title\b/,
      fileLevel: true,
      message: 'Document title is missing.',
      why: 'A title is required for accessibility and appears in tabs, bookmarks, and search results.',
      fix: 'Add a descriptive <title> element inside the head.',
    },
    {
      id: 'scan-web-css-important',
      category: 'smell',
      severity: 'info',
      languages: ['css'],
      pattern: /!important\b/,
      message: '!important overrides the cascade.',
      why: 'Important declarations make styles hard to reason about and usually trigger more overrides.',
      fix: 'Increase selector specificity or restructure the styles instead of forcing the rule.',
    },
    {
      id: 'scan-web-css-expression',
      category: 'vulnerability',
      severity: 'error',
      languages: ['css'],
      pattern: /expression\s*\(/,
      message: 'CSS expression() executes script.',
      why: 'Legacy IE evaluates the expression as JavaScript, which can run attacker-controlled code.',
      fix: 'Remove the expression and compute the value with JavaScript or a static style.',
    },
    {
      id: 'scan-web-css-empty-ruleset',
      category: 'smell',
      severity: 'info',
      languages: ['css'],
      pattern: /\{\s*\}/,
      message: 'Empty CSS ruleset.',
      why: 'An empty block has no effect and usually means dead or unfinished code.',
      fix: 'Remove the ruleset or fill in the declarations it was meant to contain.',
    },
    {
      id: 'scan-html-table-no-th',
      category: 'bug',
      severity: 'warning',
      languages: ['html'],
      pattern: /<[Tt][Hh][\s>]/,
      fileLevel: true,
      message: 'Table has no header cells.',
      why: 'A data table without th elements gives screen readers no header association for the cells.',
      fix: 'Mark header cells with <th scope="col"> or <th scope="row">.',
    },
    {
      id: 'scan-web-css-zoom',
      category: 'smell',
      severity: 'info',
      languages: ['css'],
      pattern: /\bzoom\s*:/,
      message: 'Non-standard zoom property.',
      why: 'zoom is not part of the CSS specification and behaves differently across browsers.',
      fix: 'Use transform: scale() or adjust layout dimensions instead.',
    },
    {
      id: 'scan-web-xml-doctype-system',
      category: 'vulnerability',
      severity: 'warning',
      languages: ['xml'],
      pattern: /<!DOCTYPE[^>]+SYSTEM\b/,
      message: 'DOCTYPE declares an external SYSTEM entity.',
      why: 'A parser that resolves external entities can be tricked into reading local files or making requests (XXE).',
      fix: 'Disable external entity resolution in the parser and remove the SYSTEM declaration.',
    },
    {
      id: 'scan-web-xml-xsl',
      category: 'hotspot',
      severity: 'info',
      languages: ['xml'],
      pattern: /\bxsl:/,
      message: 'XSLT constructs present.',
      why: 'XSLT processing can read files and execute extensions if the input is untrusted.',
      fix: 'Confirm the stylesheet is trusted and disable extension functions and external access.',
    },
  ],
};
