export type SettingTab = 'provider' | 'behavior' | 'display' | 'about';

export interface SettingDef {
  key: string;
  tab: SettingTab;
  group: string;
  label: string;
  description: string;
  type: 'boolean' | 'string' | 'number' | 'enum';
  options?: string[];
  min?: number;
  max?: number;
}

export const SETTINGS_SCHEMA: SettingDef[] = [
  {
    key: 'preset',
    tab: 'provider',
    group: 'Connection',
    label: 'Provider',
    description: 'The connected provider preset.',
    type: 'enum',
    options: ['openai', 'anthropic', 'gemini', 'openrouter', 'groq', 'deepseek', 'ollama', 'lmstudio', 'custom'],
  },
  {
    key: 'model',
    tab: 'provider',
    group: 'Connection',
    label: 'Model',
    description: 'Model id used for chat, planning, and execution.',
    type: 'string',
  },
  {
    key: 'baseUrl',
    tab: 'provider',
    group: 'Connection',
    label: 'Base URL',
    description: 'Override the provider base URL. Empty uses the preset default.',
    type: 'string',
  },

  {
    key: 'sandbox',
    tab: 'behavior',
    group: 'Safety',
    label: 'Sandbox terminal commands',
    description: 'Restricts command writes to the workspace and common caches. The approval card can bypass it per command.',
    type: 'enum',
    options: ['off', 'workspace-write'],
  },
  {
    key: 'autoApproveTerminal',
    tab: 'behavior',
    group: 'Safety',
    label: 'Auto-approve terminal commands',
    description: 'Skip the Allow/Deny card for commands.',
    type: 'boolean',
  },
  {
    key: 'autoApproveEdits',
    tab: 'behavior',
    group: 'Safety',
    label: 'Auto-approve file edits',
    description: 'Apply write_file, edit_file, and apply_patch without asking for approval.',
    type: 'boolean',
  },
  {
    key: 'autoApproveMcp',
    tab: 'behavior',
    group: 'Safety',
    label: 'Auto-approve MCP tools',
    description: 'Run MCP tool calls without asking for approval.',
    type: 'boolean',
  },
  {
    key: 'safeCommandsOnly',
    tab: 'behavior',
    group: 'Safety',
    label: 'Auto-run only safe commands',
    description: 'When terminal auto-approve is on, only read-only commands (ls, cat, git status, npm test, ...) run automatically; everything else asks first.',
    type: 'boolean',
  },
  {
    key: 'yolo',
    tab: 'behavior',
    group: 'Safety',
    label: 'YOLO mode',
    description: 'Auto-approve everything: edits, all commands, and MCP tools. Bypasses every approval check.',
    type: 'boolean',
  },

  {
    key: 'headerTimeout',
    tab: 'behavior',
    group: 'Behavior',
    label: 'Response header timeout (s)',
    description: 'Abort a model request when response headers take longer than this. 0 disables the timeout.',
    type: 'number',
    min: 0,
  },
  {
    key: 'streamIdleTimeout',
    tab: 'behavior',
    group: 'Behavior',
    label: 'Stream idle timeout (s)',
    description: 'Abort a streaming model response when no chunk arrives for this long. 0 disables the timeout.',
    type: 'number',
    min: 0,
  },

  {
    key: 'checkDiagnostics',
    tab: 'behavior',
    group: 'Accuracy',
    label: 'Feed diagnostics back after edits',
    description: 'Language-server errors for touched files are added to the tool result so the agent fixes its own mistakes.',
    type: 'boolean',
  },
  {
    key: 'parallelTools',
    tab: 'behavior',
    group: 'Accuracy',
    label: 'Parallel read-only tools',
    description: 'Run independent read-only tool calls at the same time.',
    type: 'boolean',
  },
  {
    key: 'memory',
    tab: 'behavior',
    group: 'Accuracy',
    label: 'Project memory',
    description: 'Save and recall durable project facts across sessions.',
    type: 'boolean',
  },
  {
    key: 'semanticIndex',
    tab: 'behavior',
    group: 'Accuracy',
    label: 'Semantic search',
    description: 'Enable semantic_search using the bundled local embedding model.',
    type: 'boolean',
  },
  {
    key: 'embeddingsProvider',
    tab: 'behavior',
    group: 'Accuracy',
    label: 'Embeddings source',
    description: 'Local bundled model (offline) or your provider’s embeddings API.',
    type: 'enum',
    options: ['local', 'api'],
  },
  {
    key: 'autoCompact',
    tab: 'behavior',
    group: 'Context',
    label: 'Auto compaction',
    description: 'Summarize the conversation when it approaches the context limit.',
    type: 'boolean',
  },
  {
    key: 'contextLimitTokens',
    tab: 'behavior',
    group: 'Context',
    label: 'Context limit override',
    description: 'Fallback context window used only when the model is not in the model catalog.',
    type: 'number',
    min: 16_000,
    max: 2_000_000,
  },
  {
    key: 'pasteFileLines',
    tab: 'behavior',
    group: 'Input',
    label: 'Save large pastes to a file',
    description:
      'Pasted text longer than this many lines is saved under .dev-first/pastes and referenced in the message instead of filling the prompt.',
    type: 'number',
    min: 20,
  },

  {
    key: 'autocomplete',
    tab: 'behavior',
    group: 'Autocomplete',
    label: 'Inline completions',
    description: 'Ghost-text completions in the editor.',
    type: 'boolean',
  },
  {
    key: 'autocompleteFallback',
    tab: 'behavior',
    group: 'Autocomplete',
    label: 'Chat fallback',
    description: 'Ask the connected chat model when no FIM model applies. Throttled to one call per second.',
    type: 'boolean',
  },
  {
    key: 'autocompleteModel',
    tab: 'behavior',
    group: 'Autocomplete',
    label: 'Autocomplete model',
    description: 'FIM model id. Empty means auto per provider.',
    type: 'string',
  },

  {
    key: 'resources',
    tab: 'display',
    group: 'Chat',
    label: 'Learn more button',
    description: 'AI-suggested, verified learning resources for plans and walkthroughs.',
    type: 'boolean',
  },
  {
    key: 'mcpDisplay',
    tab: 'display',
    group: 'Chat',
    label: 'MCP output rendering',
    description: 'How MCP tool output is rendered in the transcript.',
    type: 'enum',
    options: ['markdown', 'plain'],
  },
  {
    key: 'soundOnFinish',
    tab: 'display',
    group: 'Notifications',
    label: 'Sound when a task finishes',
    description: 'Play a short tone when a run completes.',
    type: 'boolean',
  },
  {
    key: 'notifyOnFinish',
    tab: 'display',
    group: 'Notifications',
    label: 'VS Code notification when a task finishes',
    description: 'Show a notification with a shortcut back to the panel.',
    type: 'boolean',
  },
  {
    key: 'notifyOnComplete',
    tab: 'display',
    group: 'Notifications',
    label: 'Notify when a task completes',
    description: 'Show a VS Code notification when a run finishes successfully.',
    type: 'boolean',
  },
  {
    key: 'notifyOnError',
    tab: 'display',
    group: 'Notifications',
    label: 'Notify on errors',
    description: 'Show a VS Code error notification when a run fails.',
    type: 'boolean',
  },
  {
    key: 'notifySound',
    tab: 'display',
    group: 'Notifications',
    label: 'Notification sound',
    description: 'Play a short sound when a task completes or fails.',
    type: 'enum',
    options: ['off', 'chime', 'beep'],
  },
  {
    key: 'notifyOnInput',
    tab: 'display',
    group: 'Notifications',
    label: 'Notify when Dev-First needs you',
    description: 'Show a notification when a plan awaits approval, a command needs Allow/Deny, or the agent asked a question.',
    type: 'boolean',
  },
  {
    key: 'keepAwake',
    tab: 'behavior',
    group: 'Attention',
    label: 'Keep the computer awake while working',
    description: 'Prevent sleep while a plan is running (macOS caffeinate).',
    type: 'boolean',
  },
  {
    key: 'scanMaxFiles',
    tab: 'behavior',
    group: 'Scanning',
    label: 'Maximum indexed files',
    description: 'Stop indexing after this many files. Raise it for very large repositories.',
    type: 'number',
    min: 100,
    max: 20000,
  },
  {
    key: 'scanIgnore',
    tab: 'behavior',
    group: 'Scanning',
    label: 'Ignore globs',
    description: 'Comma-separated glob patterns for files to skip when scanning.',
    type: 'string',
  },
  {
    key: 'scanAiModel',
    tab: 'behavior',
    group: 'Scanning',
    label: 'AI scan model',
    description: 'Model used for the AI scan. Empty uses the main chat model.',
    type: 'string',
  },
  {
    key: 'architecture',
    tab: 'display',
    group: 'Chat',
    label: 'Architecture view',
    description: 'Show the Architecture button that maps the codebase into domains, subsystems, and components.',
    type: 'boolean',
  },
];

export const SETTING_KEYS = new Set(SETTINGS_SCHEMA.map((setting) => setting.key));
